name: Deploy RELEASE

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Render RELEASE Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_RELEASE_DEPLOY_HOOK }}"
