name: Deploy to Pantheon DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - run: composer validate

      - run: composer install --no-interaction --prefer-dist

      - name: Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.9.0
        with:
          ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
          machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          site: ${{ secrets.PANTHEON_SITE_NAME }}
